/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ExpenseUpdateManyWithoutReportsInput } from "./ExpenseUpdateManyWithoutReportsInput";
import { ValidateNested, IsOptional, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { IncomeUpdateManyWithoutReportsInput } from "./IncomeUpdateManyWithoutReportsInput";
import { EnumReportReportType } from "./EnumReportReportType";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
@InputType()
class ReportUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ExpenseUpdateManyWithoutReportsInput,
  })
  @ValidateNested()
  @Type(() => ExpenseUpdateManyWithoutReportsInput)
  @IsOptional()
  @Field(() => ExpenseUpdateManyWithoutReportsInput, {
    nullable: true,
  })
  expense?: ExpenseUpdateManyWithoutReportsInput;

  @ApiProperty({
    required: false,
    type: () => IncomeUpdateManyWithoutReportsInput,
  })
  @ValidateNested()
  @Type(() => IncomeUpdateManyWithoutReportsInput)
  @IsOptional()
  @Field(() => IncomeUpdateManyWithoutReportsInput, {
    nullable: true,
  })
  income?: IncomeUpdateManyWithoutReportsInput;

  @ApiProperty({
    required: false,
    enum: EnumReportReportType,
  })
  @IsEnum(EnumReportReportType)
  @IsOptional()
  @Field(() => EnumReportReportType, {
    nullable: true,
  })
  reportType?: "Expense" | "Income" | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}
export { ReportUpdateInput };
